version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:      
      - 27017:27017

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/ect/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/ect/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - 3000:3000

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backendwebapi:
    build:
      context: .
    ports:      
      - 5001:80
    depends_on:
      - mongo

volumes:
  prometheus-data:

